### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by PenetratingShot** [talonbragg/EDIT#3]
Wow... you just had to use Wing didn't you? ¬_¬

What evs

**Comment by talonbragg** [comment]
lololololololololololololololololololololololololololololololololololollloloollololololololololoololololollolololololololololololololololoolo!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
